version: 2

models:
  - name: conversion_data_transformed
    description: "Transformed data for conversion metrics analysis"
    columns:
      - name: ad_id
        description: "ID of the ad"
        tests:
          - not_null
          - unique
      - name: xyz_campaign_id
        description: "Campaign ID"
        tests:
          - not_null
      - name: age
        description: "Age group"
        tests:
          - not_null
      - name: gender
        description: "Gender"
        tests:
          - not_null
      - name: interest
        description: "Total interest"
        tests:
          - not_null
          - expression_is_positive
      - name: impressions
        description: "Total impressions"
        tests:
          - not_null
          - expression_is_positive
      - name: clicks
        description: "Total clicks"
        tests:
          - not_null
          - expression_is_positive
      - name: spent
        description: "Total spent"
        tests:
          - not_null
          - expression_is_positive
      - name: total_conversion
        description: "Total conversions"
        tests:
          - not_null
          - expression_is_positive
      - name: approved_conversion
        description: "Approved conversions"
        tests:
          - not_null
          - expression_is_positive
      - name: ctr
        description: "Click-through rate"
        tests:
          - not_null
          - expression_is_positive
      - name: cpc
        description: "Cost per click"
        tests:
          - not_null
          - expression_is_positive
      - name: cpm
        description: "Cost per thousand impressions"
        tests:
          - not_null
          - expression_is_positive
      - name: cpa
        description: "Cost per acquisition"
        tests:
          - not_null
          - expression_is_positive
      - name: conversion_rate_clicks
        description: "Conversion rate: orders by clicks"
        tests:
          - not_null
          - expression_is_positive
      - name: approved_conversion_rate_clicks
        description: "Approved conversion rate by clicks"
        tests:
          - not_null
          - expression_is_positive
      - name: approved_conversion_rate_orders
        description: "Conversion rate: orders by approved orders"
        tests:
          - not_null
          - expression_is_positive
      - name: cost_per_approved_conversion
        description: "Cost per approved conversion"
        tests:
          - not_null
          - expression_is_positive